provider: local
ClusterLoader:
  cleanup: false
  projects:
  - num: 20
    basename: cnv-vm-testing-cirros
    tuning: default
    ifexists: delete
    templates:
    - num: NUMBER_OF_VMS
      basename: vm-cirros-
      file: cnv_vm_cirros_template_64m.json

  tuningsets:
  - name: default
    pods:
      stepping:
        stepsize: 50
        pause: 20
      ratelimit:
        delay: 250 ms